services:
    app:
        image: noeldemartin/rem
        volumes:
            - ./database/database.sqlite:/app/database/database.sqlite
            - ./storage:/app/storage
            - ./.env:/app/.env
        networks:
            default:
                aliases:
                    - rem

networks:
    default:
        name: nginx-agora
        external: true
