#!/usr/bin/env bash

function rem-docker-compose() {
    docker compose -f $base_dir/docker-compose.yml $@
}

function rem-cli() {
    $base_dir/rem $@
}

function rem_is_running() {
    if [ -z $(rem-docker-compose ps --quiet | head -n 1) ]; then
        false
    fi
}

export base_dir=`cd $(readlink -f $0 | xargs dirname) && pwd`
export scripts_dir="$base_dir/scripts"
export -f rem-docker-compose
export -f rem-cli
export -f rem_is_running

command=$1

case "$command" in
    'help' | '' )
        echo 'rem install          | initialize app files'
        echo 'rem start            | start app services'
        echo 'rem restart          | restart app services'
        echo 'rem stop             | stop app services'
        echo 'rem update           | update app and restart'
        echo 'rem permissions      | set file permissions'
        echo 'rem publish-assets   | publish assets into /public folder'
        echo 'rem shell {service?} | open shell in a running container'
        echo 'rem docker-compose   | run docker-compose command'
        ;;
    'stop' )
        rem-docker-compose down
        ;;
    'restart' )
        rem-cli stop
        rem-cli start
        ;;
    'docker-compose' )
        rem-docker-compose ${@:2}
        ;;
    'install' | 'start' | 'update' | 'permissions' | 'publish-assets' | 'shell' )
        $scripts_dir/$command.sh ${@:2}
        ;;
    * )
        echo "Unknown command '$command'"
        ;;
esac
