version: '3'
services:
    app:
        image: noeldemartin/rem
        volumes:
            - ./storage:/app/storage
            - ./.env:/app/.env
        networks:
            default:
                aliases:
                    - rem

networks:
    default:
        external:
            name: nginx-agora
