name: DockerHub
on:
  push:
    branches:
      - 'main'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Prepare
        run: mv headless/Dockerfile ./
      - name: Build
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/rem:$(git rev-parse HEAD)
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rem:$(git rev-parse HEAD)
