name: Headless
on:
  push:
    branches:
      - 'main'

jobs:
  headless:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update headless branch
        run: ./.github/scripts/update-headless.sh
