name: Release
on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Pull image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rem:$GITHUB_SHA
      - name: Publish release tag
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rem:$GITHUB_SHA ${{ secrets.DOCKERHUB_USERNAME }}/rem:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rem:${{ github.ref_name }}
      - name: Publish latest tag
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rem:$GITHUB_SHA ${{ secrets.DOCKERHUB_USERNAME }}/rem:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rem:latest
